prompt --application/user_interfaces
begin
wwv_flow_api.create_user_interface(
 p_id=>wwv_flow_api.id(6877050287267426)
,p_ui_type_name=>'DESKTOP'
,p_display_name=>'Desktop'
,p_display_seq=>10
,p_use_auto_detect=>false
,p_is_default=>true
,p_theme_id=>42
,p_home_url=>'f?p=&APP_ID.:HOME:&SESSION.::&DEBUG.:RP'
,p_login_url=>'f?p=&APP_ID.:LOGIN:&SESSION.'
,p_theme_style_by_user_pref=>false
,p_global_page_id=>0
,p_navigation_list_id=>wwv_flow_api.id(34303351556032323)
,p_navigation_list_position=>'TOP'
,p_navigation_list_template_id=>wwv_flow_api.id(6850610093267411)
,p_nav_list_template_options=>'#DEFAULT#:js-tabLike'
,p_css_file_urls=>'#WORKSPACE_IMAGES#blog040000/style.css?version=#APP_VERSION#'
,p_javascript_file_urls=>'#WORKSPACE_IMAGES#blog040000/blog.js?version=#APP_VERSION#'
,p_nav_bar_type=>'LIST'
,p_nav_bar_list_id=>wwv_flow_api.id(6876779235267426)
,p_nav_bar_list_template_id=>wwv_flow_api.id(6848359906267410)
,p_nav_bar_template_options=>'#DEFAULT#'
);
end;
/
