prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/blog_oracle_cloud_api_key.sql
@@workspace/credentials/blog_open_ai_api_key.sql
@@workspace/credentials/blog_google_oauth2.sql
@@workspace/remote_servers/blog_language_ai.sql
@@workspace/remote_servers/blog_open_ai.sql
@@workspace/remote_servers/blog_object_storage.sql
@@application/shared_components/data_profiles/list_bucket_objects.sql
@@application/shared_components/data_profiles/blog_language_ai.sql
@@application/shared_components/web_sources/blog_object_storage_object.sql
@@application/shared_components/web_sources/blog_language_ai.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/admin_authentication.sql
@@application/shared_components/navigation/lists/oracle_cloud_api_key.sql
@@application/shared_components/navigation/lists/configuration.sql
@@application/shared_components/navigation/lists/ai_configuration.sql
@@application/shared_components/navigation/lists/object_storage.sql
@@application/shared_components/navigation/lists/public_application_links.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/css_admin_css.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/css_admin_min_css.sql
@@application/shared_components/files/js_admin_min_js.sql
@@application/shared_components/files/js_admin_js.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/bloggers.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/initialize_after_authentication.sql
@@application/shared_components/logic/application_processes/get_blogger_details.sql
@@application/shared_components/logic/application_processes/initialize_new_session.sql
@@application/shared_components/logic/application_items/g_blogger_id.sql
@@application/shared_components/logic/application_items/g_blogger_name.sql
@@application/shared_components/logic/application_items/g_pub_app_id.sql
@@application/shared_components/logic/application_computations/p501_display_date_format.sql
@@application/shared_components/logic/application_computations/p501_input_date_format.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/categories.sql
@@application/shared_components/user_interface/lovs/comment_flag_code.sql
@@application/shared_components/user_interface/lovs/comment_flag_text.sql
@@application/shared_components/user_interface/lovs/comment_status_code.sql
@@application/shared_components/user_interface/lovs/comment_staus_text.sql
@@application/shared_components/user_interface/lovs/file_directories.sql
@@application/shared_components/user_interface/lovs/file_sync_action.sql
@@application/shared_components/user_interface/lovs/is_active.sql
@@application/shared_components/user_interface/lovs/link_status.sql
@@application/shared_components/user_interface/lovs/post_status.sql
@@application/shared_components/user_interface/lovs/post_tags.sql
@@application/shared_components/user_interface/lovs/post_tags_hidden.sql
@@application/shared_components/user_interface/lovs/post_tags_visible.sql
@@application/shared_components/user_interface/lovs/sentiment.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/yes_no.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/blog_btn_ai_assistant.sql
@@application/shared_components/user_interface/shortcuts/blog_btn_post_description.sql
@@application/shared_components/user_interface/shortcuts/blog_btn_post_title.sql
@@application/shared_components/user_interface/shortcuts/blog_btn_post_category.sql
@@application/shared_components/user_interface/shortcuts/blog_btn_post_tags.sql
@@application/shared_components/user_interface/shortcuts/blog_btn_post_body.sql
@@application/shared_components/email/templates/blog_reply_to_comment_notify.sql
@@application/shared_components/security/authentications/apex.sql
@@application/shared_components/security/authentications/google.sql
@@application/shared_components/plugins/template_component/theme_42_footer_link_custom.sql
@@application/shared_components/plugins/template_component/theme_42_icon_custom.sql
@@application/shared_components/plugins/template_component/theme_42_button_custom_2.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00201.sql
@@application/pages/page_00202.sql
@@application/pages/page_00300.sql
@@application/pages/page_00301.sql
@@application/pages/page_00302.sql
@@application/pages/page_00303.sql
@@application/pages/page_00501.sql
@@application/pages/page_09999.sql
@@application/pages/page_20010.sql
@@application/pages/page_20011.sql
@@application/pages/page_20012.sql
@@application/pages/page_20013.sql
@@application/pages/page_20014.sql
@@application/pages/page_20015.sql
@@application/pages/page_20016.sql
@@application/pages/page_20017.sql
@@application/pages/page_20018.sql
@@application/pages/page_20019.sql
@@application/pages/page_20020.sql
@@application/pages/page_20100.sql
@@application/pages/page_30000.sql
@@application/pages/page_30020.sql
@@application/pages/page_30021.sql
@@application/pages/page_30022.sql
@@application/pages/page_30023.sql
@@application/pages/page_30024.sql
@@application/pages/page_30025.sql
@@application/pages/page_30026.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_database_objects.sql
@@application/deployment/install/install_metadata.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
