--------------------------------------------------------
--  File created - Saturday-April-25-2020
--------------------------------------------------------
REM INSERTING into BLOG_040000.BLOG_FEATURES
SET DEFINE OFF;
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_MODERATE_COMMENTS','BLOG_FEATURE_GROUP_COMMENTS',null,'20');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_SEARCH_FILES','BLOG_FEATURE_GROUP_SEARCH',null,'130');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_SEARCH_LINKS','BLOG_FEATURE_GROUP_SEARCH',null,'120');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_CATEGORY','BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,'60');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_SEARCH_POSTS','BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,'40');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_ARCHIVE','BLOG_FEATURE_GROUP_PAGE',null,'50');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_LATEST_POSTS','BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,'70');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_LINKS','BLOG_FEATURE_GROUP_PAGE',null,'90');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_ALLOW_COMMENTS','BLOG_FEATURE_GROUP_COMMENTS',null,'10');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_RSS','BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,'80');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_FILES','BLOG_FEATURE_GROUP_PAGE',null,'100');
Insert into BLOG_040000.BLOG_FEATURES (BUILD_OPTION_NAME,BUILD_OPTION_GROUP,BUILD_OPTION_PARENT,DISPLAY_SEQ) values ('BLOG_FEATURE_POST_PAGINATION','BLOG_FEATURE_GROUP_POST',null,'30');
