REM INSERTING into BLOG_SETTINGS
SET DEFINE OFF;
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','1','APP_GROUP','STRING','INTERNAL','BLOG_040000',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','2','VERSION','STRING','INTERNAL','4.0.0.72',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','3','COMMENT_WHITELIST_TAGS','STRING','INTERNAL','<b>,</b>,<i>,</i>,<u>,</u>,<code>,</code>',null);

Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','10','G_APP_NAME','STRING','UI','Example Blog',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','20','G_APP_DESC','STRING','UI','Enter blog description here',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','30','G_DATE_FORMAT','STRING','UI','fmDD Mon YYYY',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','40','G_POST_TITLE_DATE_FORMAT','STRING','UI','fmDay"," Month DD"," YYYY',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','50','G_ARCHIVE_DATE_FORMAT','STRING','UI','fmMonth, YYYY',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','60','P1_REPORT_ROWS','INTEGER','UI','10',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','70','P2_REPORT_ROWS','INTEGER','UI','10',null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','80','G_SEARCH_ROWS','INTEGER','UI','10',null);

Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('0','100','CANONICAL_URL','STRING','SEO',apex_util.host_url('SCRIPT'),null);
Insert into BLOG_SETTINGS (IS_NULLABLE,DISPLAY_SEQ,ATTRIBUTE_NAME,DATA_TYPE,GROUP_NAME,ATTRIBUTE_VALUE,BUILD_OPTION_NAME) values ('1','110','RSS_URL','STRING','SEO','','BLOG_FEATURE_RSS');


begin
  dbms_mview.refresh('BLOG_ITEMS_INIT', 'C');
end;
/
