prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/credentials/abstract_email_validation_api_key.sql
@@application/shared_components/remote_servers/abstract.sql
@@application/shared_components/data_profiles/email_validation_api.sql
@@application/shared_components/web_sources/abstract_email_validation_api.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/post_categories.sql
@@application/shared_components/navigation/lists/latest_posts.sql
@@application/shared_components/navigation/lists/post_archives.sql
@@application/shared_components/navigation/lists/tabs.sql
@@application/shared_components/navigation/lists/footer_modal_pages.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/ico_apple_touch_icon_png.sql
@@application/shared_components/files/ico_favicon_32x32_png.sql
@@application/shared_components/files/ico_favicon_16x16_png.sql
@@application/shared_components/files/ico_favicon_ico.sql
@@application/shared_components/files/ico_site_webmanifest.sql
@@application/shared_components/files/ico_android_chrome_192x192_png.sql
@@application/shared_components/files/ico_android_chrome_512x512_png.sql
@@application/shared_components/files/ico_about_txt.sql
@@application/shared_components/files/css_rss_xsl_css.sql
@@application/shared_components/files/js_blog_js.sql
@@application/shared_components/files/css_style_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/initiatize_items.sql
@@application/shared_components/logic/application_processes/redirect_to_search_page.sql
@@application/shared_components/logic/application_items/g_app_desc.sql
@@application/shared_components/logic/application_items/g_app_name.sql
@@application/shared_components/logic/application_items/g_app_version.sql
@@application/shared_components/logic/application_items/g_archive_date_format.sql
@@application/shared_components/logic/application_items/g_date_format.sql
@@application/shared_components/logic/application_items/g_latest_post_rows.sql
@@application/shared_components/logic/application_items/g_post_title_date_format.sql
@@application/shared_components/logic/application_items/g_rss_url.sql
@@application/shared_components/logic/application_items/g_search_rows.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/blog_footer_link_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/blog_post_report.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/blog_content.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/blog_rss_link.sql
@@application/shared_components/user_interface/shortcuts/blog_meta_robots_noindex.sql
@@application/shared_components/user_interface/shortcuts/blog_rss_anchor.sql
@@application/shared_components/user_interface/shortcuts/blog_meta_home_description.sql
@@application/shared_components/user_interface/shortcuts/blog_meta_post_description.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_post.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_category.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_tag.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_archive.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_tab.sql
@@application/shared_components/user_interface/shortcuts/blog_powered_by.sql
@@application/shared_components/email/templates/blog_new_comment_notify.sql
@@application/shared_components/security/authentications/no_authentication.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/shared_components/plugins/item_type/fi_jaris_math_question_field.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00006.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_01001.sql
@@application/pages/page_01002.sql
@@application/pages/page_01003.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_metadata.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
