REM INSERTING into BLOG_PARAMS
SET DEFINE OFF;
Insert into BLOG_PARAMS (IS_INTERNAL,IS_NULLABLE,DISPLAY_SEQ,PARAM_NAME,PARAM_LABEL,DATA_TYPE,GROUP_NAME,HELP_TEXT,PARENT_NAME,PARAM_VALUE,VALIDATION_EXP,PROCESS_EXP) values ('1','0','1','G_ARTICLE_TITLE_DATE_FORMAT','Title date format','STRING','UI','Public application article title date format',null,'fmDay"," Month DD"," YYYY',null,null);
Insert into BLOG_PARAMS (IS_INTERNAL,IS_NULLABLE,DISPLAY_SEQ,PARAM_NAME,PARAM_LABEL,DATA_TYPE,GROUP_NAME,HELP_TEXT,PARENT_NAME,PARAM_VALUE,VALIDATION_EXP,PROCESS_EXP) values ('1','1','2','RSS_URL','RSS feed URL','STRING','SEO','Public application RSS feed URL',null,null,null,null);
Insert into BLOG_PARAMS (IS_INTERNAL,IS_NULLABLE,DISPLAY_SEQ,PARAM_NAME,PARAM_LABEL,DATA_TYPE,GROUP_NAME,HELP_TEXT,PARENT_NAME,PARAM_VALUE,VALIDATION_EXP,PROCESS_EXP) values ('1','0','3','G_APP_DESC','Application description','STRING','UI','Blog description',null,'About Oracle Application Express (APEX) and Related Stuff',null,null);
Insert into BLOG_PARAMS (IS_INTERNAL,IS_NULLABLE,DISPLAY_SEQ,PARAM_NAME,PARAM_LABEL,DATA_TYPE,GROUP_NAME,HELP_TEXT,PARENT_NAME,PARAM_VALUE,VALIDATION_EXP,PROCESS_EXP) values ('1','0','4','G_SEARCH_ROWS','Search results per pagination','INTEGER','UI','Number of search result display per report page',null,'10',null,null);
Insert into BLOG_PARAMS (IS_INTERNAL,IS_NULLABLE,DISPLAY_SEQ,PARAM_NAME,PARAM_LABEL,DATA_TYPE,GROUP_NAME,HELP_TEXT,PARENT_NAME,PARAM_VALUE,VALIDATION_EXP,PROCESS_EXP) values ('1','0','5','G_ARTICLE_ROWS','Article per pagination','INTEGER','UI','Number of articles display per report page',null,'10',null,null);
Insert into BLOG_PARAMS (IS_INTERNAL,IS_NULLABLE,DISPLAY_SEQ,PARAM_NAME,PARAM_LABEL,DATA_TYPE,GROUP_NAME,HELP_TEXT,PARENT_NAME,PARAM_VALUE,VALIDATION_EXP,PROCESS_EXP) values ('1','0','6','G_APP_NAME','Application name','STRING','UI','Blog name',null,'Jari''s APEX Blog',null,null);
Insert into BLOG_PARAMS (IS_INTERNAL,IS_NULLABLE,DISPLAY_SEQ,PARAM_NAME,PARAM_LABEL,DATA_TYPE,GROUP_NAME,HELP_TEXT,PARENT_NAME,PARAM_VALUE,VALIDATION_EXP,PROCESS_EXP) values ('1','0','7','G_COMMENT_ROWS','Comments per pagination','INTEGER','UI','Number of comment display per report page',null,'10',null,null);
Insert into BLOG_PARAMS (IS_INTERNAL,IS_NULLABLE,DISPLAY_SEQ,PARAM_NAME,PARAM_LABEL,DATA_TYPE,GROUP_NAME,HELP_TEXT,PARENT_NAME,PARAM_VALUE,VALIDATION_EXP,PROCESS_EXP) values ('1','0','8','G_DATE_FORMAT','Application date format','STRING','UI','Public application date format',null,'fmDD Mon YYYY',null,null);

begin
  dbms_mview.refresh('BLOG_ARCHIVE_LOV,BLOG_ITEM_INIT,BLOG_POSTS_LAST20', 'CCC');
end;
/
