--REM INSERTING into BLOG_COUNTRY
--SET DEFINE OFF;
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AA','Antartica');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AC','Antigua and Barbuda');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AD','Andorra');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AE','United Arab Emirates');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AF','Afghanistan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AG','Antigua and Barbuda');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AI','Anguilla');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AL','Albania');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AM','Armenia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AN','Netherlands Antilles');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AO','Angola');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AR','Argentina');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AS','American Samoa');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AT','Austria');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AU','Australia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AW','Aruba');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('AZ','Azerbaijan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BA','Bosnia and Herzegovina');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BB','Barbados');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BD','Bangladesh');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BE','Belgium');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BF','Burkina Faso');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BG','Bulgaria');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BH','Bahrain');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BI','Burundi');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BJ','Benin');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BM','Bermuda');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BN','Brunei');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BO','Bolivia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BR','Brazil');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BS','Bahamas, The');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BT','Bhutan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BV','Bouvet Island');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BW','Botswana');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BY','Belarus');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('BZ','Belize');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CA','Canada');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CC','Cocos (Keeling) Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CD','Zaire');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CF','Central African Republic');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CG','Congo');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CH','Switzerland');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CI','Cote d''Ivoire');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CK','Cook Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CL','Chile');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CM','Cameroon');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CN','China');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CO','Colombia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CR','Costa Rica');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CU','Cuba');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CV','Cape Verde');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CX','Christmas Island');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CY','Cyprus');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('CZ','Czech Republic');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('DE','Germany');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('DJ','Djibouti');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('DK','Denmark');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('DM','Dominica');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('DO','Dominican Republic');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('DQ','Jarvis Island');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('DZ','Algeria');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('EC','Ecuador');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('EE','Estonia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('EG','Egypt');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('EH','Western Sahara');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ER','Eritrea');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ES','Spain');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ET','Ethiopia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('FI','Finland');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('FJ','Fiji');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('FK','Falkland Islands (Islas Malvinas)');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('FM','Federated States of Micronesia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('FO','Faroe Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('FQ','Baker Island');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('FR','France');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GA','Gabon');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GB','United Kingdom');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GD','Grenada');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GE','Georgia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GF','French Guiana');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GH','Ghana');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GI','Gibraltar');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GK','Guernsey');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GL','Greenland');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GM','Gambia, The');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GN','Guinea');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GO','Glorioso Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GP','Guadeloupe');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GQ','Equatorial Guinea');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GR','Greece');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GS','South Georgia and the South Sandwich Is');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GT','Guatemala');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GU','Guam');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GW','Guinea-Bissau');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GY','Guyana');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('GZ','Gaza Strip');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('HK','Hong Kong');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('HM','Heard Island & McDonald Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('HN','Honduras');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('HQ','Howland Island');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('HR','Croatia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('HT','Haiti');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('HU','Hungary');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ID','Indonesia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IE','Ireland');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IL','Israel');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IM','Man, Isle of');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IN','India');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IO','British Indian Ocean Territory');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IQ','Iraq');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IR','Iran');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IS','Iceland');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IT','Italy');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('IV','Ivory Coast');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('JE','Jersey');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('JM','Jamaica');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('JN','Jan Mayen');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('JO','Jordan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('JP','Japan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('JQ','Johnston Atoll');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('JU','Juan De Nova Island');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KE','Kenya');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KG','Kyrgyzstan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KH','Cambodia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KI','Kiribati');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KM','Comoros');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KN','St. Kitts and Nevis');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KO','Kosovo');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KP','North Korea');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KR','South Korea');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KW','Kuwait');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KY','Cayman Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('KZ','Kazakhstan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LA','Laos');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LB','Lebanon');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LC','St. Lucia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LI','Liechtenstein');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LK','Sri Lanka');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LR','Liberia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LS','Lesotho');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LT','Lithuania');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LU','Luxembourg');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LV','Latvia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('LY','Libya');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MA','Morocco');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MC','Monaco');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MD','Moldova');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MG','Madagascar');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MH','Marshall Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MK','Macedonia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ML','Mali');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MM','Myanmar (Burma)');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MN','Mongolia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MO','Macau');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MP','Northern Mariana Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MQ','Martinique');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MR','Mauritania');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MS','Montserrat');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MT','Malta');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MU','Mauritius');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MV','Maldives');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MW','Malawi');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MX','Mexico');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MY','Malaysia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('MZ','Mozambique');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NA','Namibia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NC','New Caledonia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NE','Niger');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NF','Norfolk Island');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NG','Nigeria');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NI','Nicaragua');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NL','Netherlands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NO','Norway');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NP','Nepal');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NR','Nauru');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NU','Niue');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('NZ','New Zealand');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('OM','Oman');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PA','Panama');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PE','Peru');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PF','French Polynesia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PG','Papua New Guinea');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PH','Philippines');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PK','Pakistan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PL','Poland');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PM','St. Pierre and Miquelon');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PN','Pitcairn Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PR','Puerto Rico');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PS','Occupied Palestinian Territory');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PT','Portugal');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PU','Palau');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PW','Pacific Islands (Palau)');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('PY','Paraguay');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('QA','Qatar');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('RE','Reunion');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('RO','Romania');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('RS','Serbia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('RU','Russia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('RW','Rwanda');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SA','Saudi Arabia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SB','Solomon Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SC','Seychelles');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SD','Sudan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SE','Sweden');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SG','Singapore');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SH','St. Helena');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SI','Slovenia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SJ','Svalbard');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SK','Slovakia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SL','Sierra Leone');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SM','San Marino');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SN','Senegal');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SO','Somalia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SR','Suriname');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ST','Sao Tome and Principe');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SV','El Salvador');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SY','Syria');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('SZ','Swaziland');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TC','Turks and Caicos Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TD','Chad');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TF','French Southern & Antarctic Lands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TG','Togo');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TH','Thailand');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TJ','Tajikistan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TK','Tokelau');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TM','Turkmenistan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TN','Tunisia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TO','Tonga');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TP','East Timor');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TR','Turkey');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TT','Trinidad and Tobago');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TV','Tuvalu');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TW','Taiwan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('TZ','Tanzania, United Republic of');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('UA','Ukraine');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('UG','Uganda');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('UK','United Kingdom');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('UM','United States Minor Outlying Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('US','United States');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('UV','Burkina Faso');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('UY','Uruguay');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('UZ','Uzbekistan');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('VA','Vatican');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('VC','St. Vincent and the Grenadines');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('VE','Venezuela');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('WE','West Bank');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('WF','Wallis and Futuna');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('VG','British Virgin Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('VI','Virgin Islands');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('VN','Vietnam');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('WQ','Wake Island');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('WS','Western Samoa');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('VU','Vanuatu');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('XX','(Unknown)');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('YE','Yemen');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('YT','Mayotte');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('YU','Yugoslavia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ZA','South Africa');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ZM','Zambia');
Insert into BLOG_COUNTRY (COUNTRY_CODE,COUNTRY_NAME) values ('ZW','Zimbabwe');
