-- DDL for foreign key indexes
CREATE INDEX "BLOG_COMMENTS_IX1" ON "BLOG_COMMENTS" ("POST_ID")
;
CREATE INDEX "BLOG_COMMENTS_IX2" ON "BLOG_COMMENTS" ("PARENT_ID")
;
CREATE INDEX "BLOG_COMMENT_SUBSCRIBERS_IX1" ON "BLOG_COMMENT_SUBSCRIBERS" ("EMAIL_ID")
;
CREATE INDEX "BLOG_FEATURES_IX1" ON "BLOG_FEATURES" ("BUILD_OPTION_PARENT")
;
CREATE INDEX "BLOG_FEATURES_IX2" ON "BLOG_FEATURES" ("REF_BUILD_OPTION_NAME")
;
CREATE INDEX "BLOG_INIT_ITEMS_IX1" ON "BLOG_INIT_ITEMS" ("ITEM_NAME")
;
CREATE INDEX "BLOG_POSTS_IX1" ON "BLOG_POSTS" ("BLOGGER_ID")
;
CREATE INDEX "BLOG_POSTS_IX2" ON "BLOG_POSTS" ("CATEGORY_ID")
;
CREATE INDEX "BLOG_POST_TAGS_IX1" ON "BLOG_POST_TAGS" ("TAG_ID")
;
CREATE INDEX "BLOG_SETTINGS_IX1" ON "BLOG_SETTINGS" ("BUILD_OPTION_NAME")
;
