prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/blog_oracle_cloud_api_key.sql
@@workspace/remote_servers/blog_language_ai.sql
@@application/shared_components/data_profiles/blog_language_ai_2.sql
@@application/shared_components/web_sources/blog_language_ai.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/post_categories.sql
@@application/shared_components/navigation/lists/latest_posts.sql
@@application/shared_components/navigation/lists/post_tags.sql
@@application/shared_components/navigation/lists/post_archives.sql
@@application/shared_components/navigation/lists/footer_modal_pages.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/css_style_min_css.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/css_rss_xsl_min_css.sql
@@application/shared_components/files/js_blog_min_js.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_about_txt.sql
@@application/shared_components/files/css_rss_xsl_css.sql
@@application/shared_components/files/js_blog_js.sql
@@application/shared_components/files/css_style_css.sql
@@application/plugin_settings.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/initialize_session.sql
@@application/shared_components/logic/application_processes/redirect_to_search_page.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/search_source.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/list/blog_tag_cloud.sql
@@application/shared_components/user_interface/templates/list/blog_footer_link_list.sql
@@application/shared_components/user_interface/templates/report/blog_post_report.sql
@@application/shared_components/user_interface/templates/report/blog_content.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/blog_rss_link.sql
@@application/shared_components/user_interface/shortcuts/blog_meta_robots_noindex.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_post.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_category.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_tag.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_archive.sql
@@application/shared_components/user_interface/shortcuts/blog_canonical_link_tab.sql
@@application/shared_components/user_interface/shortcuts/blog_atom_link.sql
@@application/shared_components/email/templates/blog_new_comment_notify.sql
@@application/shared_components/security/authentications/apex_authentication.sql
@@application/shared_components/plugins/template_component/theme_42_app_banner_custom.sql
@@application/shared_components/plugins/template_component/theme_42_footer_link_custom.sql
@@application/shared_components/plugins/item_type/fi_jaris_math_question_field.sql
@@application/shared_components/navigation/search_config/comments.sql
@@application/shared_components/navigation/search_config/posts.sql
@@application/shared_components/navigation/search_config/files.sql
@@application/shared_components/navigation/search_config/links.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00004.sql
@@application/pages/page_00006.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_01001.sql
@@application/pages/page_01002.sql
@@application/pages/page_01003.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_create_view_blog_v_version.sql
@@application/deployment/install/upgrade_patch_23_1_20231118.sql
@@application/deployment/install/install_metadata.sql
@@application/deployment/install/upgrade_patch_23_2_20231120.sql
@@application/deployment/install/upgrade_patch_23_2_20240414.sql
@@application/deployment/install/upgrade_patch_24_2_20250701_part_1.sql
@@application/deployment/install/upgrade_drop_text_indexes.sql
@@application/deployment/install/upgrade_database_objects_upgrade.sql
@@application/deployment/install/upgrade_create_text_indexes.sql
@@application/deployment/install/upgrade_patch_24_2_20250701_part_2.sql
@@application/deployment/install/upgrade_postupgrade.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
