ALTER TABLE  BLOG_ARTICLE ADD CONSTRAINT BLOG_ARTICLE_FK1 FOREIGN KEY (AUTHOR_ID)
      REFERENCES  BLOG_AUTHOR (AUTHOR_ID) ENABLE
/
ALTER TABLE  BLOG_ARTICLE ADD CONSTRAINT BLOG_ARTICLE_FK2 FOREIGN KEY (CATEGORY_ID)
      REFERENCES  BLOG_CATEGORY (CATEGORY_ID) ENABLE
/
ALTER TABLE  BLOG_ARTICLE_LOG ADD CONSTRAINT BLOG_ARTICLE_LOG_FK1 FOREIGN KEY (ARTICLE_ID)
      REFERENCES  BLOG_ARTICLE (ARTICLE_ID) ON DELETE CASCADE ENABLE
/
ALTER TABLE  BLOG_AUTHOR ADD CONSTRAINT BLOG_AUTHOR_FK1 FOREIGN KEY (AUTHOR_ID)
      REFERENCES  BLOG_COMMENT_USER (USER_ID) ENABLE
/
ALTER TABLE  BLOG_CATEGORY_LOG ADD CONSTRAINT BLOG_CATEGORY_LOG_FK1 FOREIGN KEY (CATEGORY_ID)
      REFERENCES  BLOG_CATEGORY (CATEGORY_ID) ON DELETE CASCADE ENABLE
/
ALTER TABLE  BLOG_COMMENT ADD CONSTRAINT BLOG_COMMENT_FK1 FOREIGN KEY (USER_ID)
      REFERENCES  BLOG_COMMENT_USER (USER_ID) ENABLE
/
ALTER TABLE  BLOG_COMMENT ADD CONSTRAINT BLOG_COMMENT_FK2 FOREIGN KEY (ARTICLE_ID)
      REFERENCES  BLOG_ARTICLE (ARTICLE_ID) ENABLE
/
ALTER TABLE  BLOG_COMMENT ADD CONSTRAINT BLOG_COMMENT_FK3 FOREIGN KEY (PARENT_ID)
      REFERENCES  BLOG_COMMENT (COMMENT_ID) ENABLE
/
ALTER TABLE  BLOG_COMMENT_NOTIFY ADD CONSTRAINT BLOG_COMMENT_NOTIFY_FK1 FOREIGN KEY (ARTICLE_ID)
      REFERENCES  BLOG_ARTICLE (ARTICLE_ID) ON DELETE CASCADE ENABLE
/
ALTER TABLE  BLOG_COMMENT_NOTIFY ADD CONSTRAINT BLOG_COMMENT_NOTIFY_FK2 FOREIGN KEY (USER_ID)
      REFERENCES  BLOG_COMMENT_USER (USER_ID) ON DELETE CASCADE DISABLE
/
ALTER TABLE  BLOG_CONTACT_MESSAGE ADD CONSTRAINT BLOG_CONTACT_MESSAGE_FK1 FOREIGN KEY (USER_ID)
      REFERENCES  BLOG_COMMENT_USER (USER_ID) ENABLE
/
ALTER TABLE  BLOG_FILE_LOG ADD CONSTRAINT BLOG_FILES_LOG_FK1 FOREIGN KEY (FILE_ID)
      REFERENCES  BLOG_FILE (FILE_ID) ON DELETE CASCADE ENABLE
/
ALTER TABLE  BLOG_PARAM ADD CONSTRAINT BLOG_PARAM_FK1 FOREIGN KEY (PARAM_PARENT)
      REFERENCES  BLOG_PARAM (PARAM_NAME) ENABLE
/
ALTER TABLE  BLOG_ARTICLE_HIT20 ADD CONSTRAINT BLOG_ARTICLE_HIT20_FK1 FOREIGN KEY (ARTICLE_ID)
      REFERENCES  BLOG_ARTICLE (ARTICLE_ID) ENABLE
/
ALTER TABLE  BLOG_ARTICLE_LAST20 ADD CONSTRAINT BLOG_ARTICLE_LAST20_FK1 FOREIGN KEY (ARTICLE_ID)
      REFERENCES  BLOG_ARTICLE (ARTICLE_ID) ENABLE
/
ALTER TABLE  BLOG_ARTICLE_TOP20 ADD CONSTRAINT BLOG_ARTICLE_TOP20_FK1 FOREIGN KEY (ARTICLE_ID)
      REFERENCES  BLOG_ARTICLE (ARTICLE_ID) ENABLE
/
ALTER TABLE  BLOG_COMMENT_LOG ADD CONSTRAINT BLOG_COMMENT_LOG_FK1 FOREIGN KEY (ARTICLE_ID)
      REFERENCES  BLOG_ARTICLE (ARTICLE_ID) ENABLE
/