--REM INSERTING into BLOG_LONG_TEXT
--SET DEFINE OFF;
Insert into BLOG_LONG_TEXT (LONG_TEXT_TYPE,LONG_TEXT_DESCRIPTION) values ('ABOUT','About page text');
Insert into BLOG_LONG_TEXT (LONG_TEXT_TYPE,LONG_TEXT_DESCRIPTION) values ('DISCLAIMER','Blog site disclaimer');
