
-- Generated by ORDS REST Data Services 19.1.0.r0921545
-- Schema: BLOG_040000  Date: Sat May 11 06:01:55 2019 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'BLOG_040000',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'blog-dev-4.0',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'Blog Static Files',
      p_base_path      => '/pub/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => 'Sharing blog static content from blog_files table');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Blog Static Files',
      p_pattern        => 'xml/feed',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Blog Static Files',
      p_pattern        => 'xml/feed',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select ''application/rss+xml'' as mime_type
  ,blog_rest.get_rss(
     p_app_alias => ''BLOG''
    ,p_lang => :p_lang
  ) as blob_content
from dual');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'Blog Static Files',
      p_pattern            => 'xml/feed',
      p_method             => 'GET',
      p_name               => 'p_lang',
      p_bind_variable_name => 'p_lang',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Blog Static Files',
      p_pattern        => 'files/:p_file_path/:p_file_name',
      p_priority       => 0,
      p_etag_type      => 'QUERY',
      p_etag_query     => 'select etag
from blog_files
where 1 = 1
and file_name = :p_file_name
and file_path = :p_file_path',
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Blog Static Files',
      p_pattern        => 'files/:p_file_path/:p_file_name',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select mime_type
  ,blob_content
from blog_files
where 1 = 1
and file_name = :p_file_name
and file_path = :p_file_path');

    
        
COMMIT;

END;