
-- Generated by ORDS REST Data Services 19.3.0.r3191521
-- Schema: BLOG_040000  Date: Sun Jan 05 08:16:50 2020 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'BLOG_040000',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'dev',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'BLOG_APPLICATION_FILES',
      p_base_path      => '/blog/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => 'Blog static content from blog_files table');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'BLOG_APPLICATION_FILES',
      p_pattern        => 'r/:p_file_name',
      p_priority       => 0,
      p_etag_type      => 'QUERY',
      p_etag_query     => 'select etag
from blog_v_files
where 1 = 1
and file_name = :p_file_name
and file_path = ''/''',
      p_comments       => 'Blog static files module (created by application)');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'BLOG_APPLICATION_FILES',
      p_pattern        => 'r/:p_file_name',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Blog static files handler (created by application)',
      p_source         => 
'select mime_type
,blob_content
from blog_v_files
where 1 = 1
and file_name = :p_file_name
and file_path = ''/''');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'BLOG_APPLICATION_FILES',
      p_pattern        => 'r/posts/:p_file_name',
      p_priority       => 0,
      p_etag_type      => 'QUERY',
      p_etag_query     => 'select etag
from blog_v_files
where 1 = 1
and file_name = :p_file_name
and file_path = ''/posts/''',
      p_comments       => 'Blog static files module (created by application)');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'BLOG_APPLICATION_FILES',
      p_pattern        => 'r/posts/:p_file_name',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Blog static files handler (created by application)',
      p_source         => 
'select mime_type
,blob_content
from blog_v_files
where 1 = 1
and file_name = :p_file_name
and file_path = ''/posts/''');

    
        
COMMIT;

END;