set define off
@BLOG_BLOGGERS_TRG.sql
@BLOG_CATEGORIES_TRG.sql
@BLOG_COMMENTS_FLAGS.sql
@BLOG_COMMENTS_TRG.sql
@BLOG_FILES_TRG.sql
@BLOG_LINK_GROUPS_TRG.sql
@BLOG_LINKS_TRG.sql
@BLOG_POSTS_TRG.sql
@BLOG_POST_TAGS_TRG.sql
@BLOG_READERS_TRG.sql
@BLOG_SETTINGS_TRG.sql
@BLOG_TAGS_TRG.sql
