prompt --application/deployment/install/upgrade_patch_24_1_20241125_part_1
begin
--   Manifest
--     INSTALL: UPGRADE-Patch 24.1.20241125 part 1
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.7'
,p_default_workspace_id=>18303204396897713
,p_default_application_id=>401
,p_default_id_offset=>44906910937164790
,p_default_owner=>'BLOG_040000'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(149055008806170771)
,p_install_id=>wwv_flow_imp.id(148135284869193288)
,p_name=>'Patch 24.1.20241125 part 1'
,p_sequence=>40
,p_script_type=>'UPGRADE'
,p_condition_type=>'EXISTS'
,p_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select 1',
'from blog_v_version',
'where 1 = 1',
'and application_date < 20241125'))
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'--  Patch 24.1.20241125 part 1',
'--------------------------------------------------------',
'--  Truncate table BLOG_INIT_ITEMS',
'--------------------------------------------------------',
'truncate table blog_init_items',
';',
'--------------------------------------------------------',
'--  Update BLOG_SETTINGS',
'--------------------------------------------------------',
'update blog_settings',
'  set attribute_name = ''P0_BLOG_APP_NAME''',
'where attribute_name = ''BLOG_APP_NAME''',
';',
'update blog_settings',
'  set attribute_name = ''P0_BLOG_APP_DESC''',
'where attribute_name = ''BLOG_APP_DESC''',
';',
'update blog_settings',
'  set display_seq = 210',
'where attribute_name = ''P0_BLOG_APP_DATE_FORMAT''',
';',
'update blog_settings',
'  set display_seq = 220',
'where attribute_name = ''P0_BLOG_POST_DATE_FORMAT''',
';',
'update blog_settings',
'  set display_seq = 310',
'where attribute_name = ''P1_BLOG_POST_ROWS''',
';',
'update blog_settings',
'  set display_seq = 320',
'where attribute_name = ''P2_BLOG_COMMENT_ROWS''',
';',
'update blog_settings',
'  set display_seq = 330',
'where attribute_name = ''G_LATEST_POST_ROWS''',
';',
'update blog_settings',
'  set display_seq = 340',
'where attribute_name = ''P0_BLOG_SEARCH_ROWS''',
';',
'update blog_settings',
'  set display_seq = 410',
'where attribute_name = ''G_COMMENT_WATCH_MONTHS''',
';',
'update blog_settings',
'  set display_seq = 510',
', attribute_group_message = ''BLOG_SETTING_GROUP_FILE_REPO''',
'where attribute_name = ''G_MAX_AGE_DOWNLOAD''',
';',
'update blog_settings',
'  set display_seq = 520',
', attribute_group_message = ''BLOG_SETTING_GROUP_FILE_REPO''',
'where attribute_name = ''G_MAX_AGE_FILE''',
';',
'update blog_settings',
'  set display_seq = 610',
', attribute_group_message = ''BLOG_SETTING_GROUP_SITEMAP''',
'where attribute_name = ''G_MAX_AGE_SITEMAP''',
';',
'update blog_settings',
'  set display_seq = 710',
', attribute_group_message = ''BLOG_SETTING_GROUP_RSS''',
'where attribute_name = ''G_MAX_AGE_RSS''',
';',
'update blog_settings',
'  set display_seq = 720',
', attribute_group_message = ''BLOG_SETTING_GROUP_RSS''',
'where attribute_name = ''G_MAX_AGE_RSS_XSL''',
';',
'update blog_settings',
'  set display_seq = 730',
', attribute_group_message = ''BLOG_SETTING_GROUP_RSS''',
'where attribute_name = ''G_RSS_URL''',
';',
'update blog_settings',
'  set display_seq = 740',
', attribute_group_message = ''BLOG_SETTING_GROUP_RSS''',
'where attribute_name = ''G_RSS_XSL_URL''',
';',
'update blog_settings',
'  set display_seq = 810',
'where attribute_name = ''G_CANONICAL_HOST''',
';',
'--------------------------------------------------------',
'--  Insert BLOG_INIT_ITEMS',
'--------------------------------------------------------',
'insert into blog_init_items(is_active, application_id, item_name)',
'select',
'  1                 as is_active',
', ai.application_id as application_id',
', ai.item_name      as item_name',
'from apex_application_items ai',
'join blog_settings s',
'  on ai.item_name = s.attribute_name',
'where 1 = 1',
'  and exists(',
'    select 1',
'    from blog_settings x1',
'    where 1 = 1',
'      and x1.attribute_name in( ''G_ADMIN_APP_ID'', ''G_PUB_APP_ID'' )',
'      and to_number( x1.attribute_value ) = ai.application_id',
'  )',
'union all',
'select',
'  1                 as is_active',
', pi.application_id as application_id',
', pi.item_name      as item_name',
'from apex_application_page_items pi',
'join blog_settings s',
'  on pi.item_name = s.attribute_name',
'where 1 = 1',
'  and exists(',
'    select 1',
'    from blog_settings x1',
'    where 1 = 1',
'      and x1.attribute_name in( ''G_ADMIN_APP_ID'', ''G_PUB_APP_ID'' )',
'      and to_number( x1.attribute_value ) = pi.application_id',
'  )',
'order by 2, 3',
';',
'--------------------------------------------------------',
'--  Insert BLOG_FEATURES',
'--------------------------------------------------------',
'insert into blog_features(is_active, display_seq, build_option_name, build_option_group)',
'  values(''1'', ''430'', ''BLOG_FEATURE_COMMENT_VERIFY'', ''BLOG_FEATURE_GROUP_COMMENTS'')',
';',
'/*',
'insert into blog_features(is_active, display_seq, build_option_name, build_option_group)',
'  values(''1'', ''450'', ''BLOG_FEATURE_MODERATE_COMMENTS_AI'', ''BLOG_FEATURE_GROUP_COMMENTS'')',
';',
'*/',
'--------------------------------------------------------',
'--  Update BLOG_FEATURES',
'--------------------------------------------------------',
'update blog_features',
'  set display_seq = ''310''',
'  , build_option_group = ''BLOG_FEATURE_GROUP_POST''',
'where build_option_name = ''BLOG_FEATURE_POST_PAGINATION''',
';',
'update blog_features',
'  set display_seq = ''410''',
'where build_option_name = ''BLOG_FEATURE_ALLOW_COMMENTS''',
';',
'update blog_features',
'  set display_seq = ''420''',
'where build_option_name = ''BLOG_FEATURE_SUBSCRIBE_COMMENTS''',
';',
'update blog_features',
'  set display_seq = ''440''',
'where build_option_name = ''BLOG_FEATURE_MODERATE_COMMENTS''',
';',
'update blog_features',
'  set display_seq = ''510''',
'where build_option_name = ''BLOG_FEATURE_MODAL_PAGES''',
';',
'update blog_features',
'  set display_seq = ''520''',
'where build_option_name = ''BLOG_FEATURE_SITEMAP''',
';',
'update blog_features',
'  set display_seq = ''530''',
'where build_option_name = ''BLOG_FEATURE_ATOM''',
';',
'--------------------------------------------------------',
'--  Insert BLOG_SETTINGS',
'--------------------------------------------------------',
'insert into blog_settings(display_seq, is_nullable, attribute_group_message, attribute_name, data_type)',
'  values(''1110'', ''1'', ''INTERNAL'', ''G_OCI_OS_PROXY_URL'', ''URL'')',
';',
'insert into blog_settings(display_seq, is_nullable, attribute_group_message, attribute_name, data_type)',
'  values(''1120'', ''1'', ''INTERNAL'', ''G_OCI_OS_BUCKET_URL'', ''URL'')',
';',
'insert into blog_settings(display_seq, is_nullable, attribute_group_message, attribute_name, data_type)',
'  values(''1130'', ''1'', ''INTERNAL'', ''G_OCI_OS_NAMESPACE'', ''STRING'')',
';',
'insert into blog_settings(display_seq, is_nullable, attribute_group_message, attribute_name, data_type)',
'  values(''1150'', ''1'', ''INTERNAL'', ''G_OCI_OS_REGION'', ''STRING'')',
';',
'insert into blog_settings(display_seq, is_nullable, attribute_group_message, attribute_name, data_type)',
'  values(''1150'', ''1'', ''INTERNAL'', ''G_OCI_OS_BUCKET'', ''STRING'')',
';',
'insert into blog_settings(display_seq, is_nullable, attribute_group_message, attribute_name, data_type)',
'  values(''1160'', ''1'', ''INTERNAL'', ''G_OCI_LANG_AI_COMPARTMENT_OCID'', ''STRING'')',
';',
'--------------------------------------------------------',
'--  Alter table BLOG_FILES',
'--------------------------------------------------------',
'alter table blog_files rename column file_name to file_path',
';',
'alter table blog_files modify blob_content null',
';',
'alter table blog_files add(',
'  md5 varchar2( 256 char )',
', etag varchar2( 256 char )',
', apex$sync_step_static_id varchar2( 255 byte )',
', apex$row_sync_timestamp timestamp with time zone',
', file_dir  varchar2(260 char) generated always as ( ''/'' || substr( file_path, 1, instr( file_path, ''/'', - 1 ) ) ) virtual not null',
', file_name varchar2(260 char) generated always as ( substr( file_path, instr( file_path, ''/'', - 1 ) + 1 ) ) virtual not null',
')',
';',
'alter table blog_files move',
';',
'alter index blog_files_uk1 rebuild',
';',
'alter index blog_files_pk rebuild',
';',
'--------------------------------------------------------',
'--  Alter table BLOG_FEATURES',
'--------------------------------------------------------',
'alter table blog_features drop column build_option_parent',
';',
'--------------------------------------------------------',
'--  Rename table BLOG_COMMENTS constraints',
'--------------------------------------------------------',
'alter table blog_comments rename constraint blog_comment_ck1 to blog_comments_ck1',
';',
'alter table blog_comments rename constraint blog_comment_ck2 to blog_comments_ck2',
';',
'--------------------------------------------------------',
'--  Alter table BLOG_COMMENTS',
'--------------------------------------------------------',
'alter table blog_comments add(',
'  comment_preview varchar2(4000 byte)',
');',
'--------------------------------------------------------',
'--  Create table BLOG_COMMENT_SENTIMENTS',
'--------------------------------------------------------',
'create table blog_comment_sentiments(',
'  id number( 38, 0 ) not null,',
'  row_version number( 38, 0 ) not null,',
'  created_on timestamp( 6 ) with local time zone not null,',
'  created_by varchar2( 256 char ) not null,',
'  changed_on timestamp( 6 ) with local time zone not null,',
'  changed_by varchar2( 256 char ) not null,',
'  comment_id number( 38, 0 ) not null,',
'  sentiment_json varchar2(4000 byte) not null,',
'  constraint blog_comment_sentiments_pk primary key( id ),',
'  constraint blog_comment_sentiments_uk1 unique( comment_id ),',
'  constraint blog_comment_sentiments_ck1 check( row_version > 0 ),',
'  constraint blog_comment_sentiments_ck2 check( sentiment_json is json ),',
'  constraint blog_comment_sentiments_fk1 foreign key( comment_id ) references blog_comments (id) on delete cascade',
');',
'--------------------------------------------------------',
'--  Create table BLOG_SETTING_FEATURES',
'--------------------------------------------------------',
'create table blog_setting_features(',
'  id number( 38, 0 ) not null,',
'  row_version number( 38, 0 ) not null,',
'  created_on timestamp( 6 ) with local time zone not null,',
'  created_by varchar2( 256 char ) not null,',
'  changed_on timestamp( 6 ) with local time zone not null,',
'  changed_by varchar2( 256 char ) not null,',
'  attribute_name varchar2( 128 char ) not null,',
'  build_option_name varchar2( 256 char ) not null,',
'  build_option_status varchar2( 10 char ) not null,',
'  constraint blog_setting_features_pk primary key( id ),',
'  constraint blog_setting_features_uk1 unique( attribute_name ),',
'  constraint blog_setting_features_ck1 check( row_version > 0 ),',
'  constraint blog_setting_features_ck2 check( build_option_status in( ''EXCLUDE'', ''INCLUDE'' ) ),',
'  constraint blog_setting_features_fk1 foreign key( attribute_name ) references blog_settings( attribute_name )',
');',
'--------------------------------------------------------',
'--  Create Table BLOG_FEATURE_PARENTS',
'--------------------------------------------------------',
'create table blog_feature_parents(',
'  id number( 38, 0 ) not null,',
'  row_version number( 38, 0 ) not null,',
'  created_on timestamp( 6 ) with local time zone not null,',
'  created_by varchar2( 256 char ) not null,',
'  changed_on timestamp( 6 ) with local time zone not null,',
'  changed_by varchar2( 256 char ) not null,',
'  is_active number( 1, 0 ) not null,',
'  build_option_name varchar2( 256 char ) not null,',
'  build_option_parent varchar2( 256 char ),',
'  constraint blog_feature_parents_pk primary key( id ),',
'  constraint blog_feature_parents_uk1 unique( build_option_name ),',
'  constraint blog_feature_parents_ck1 check( row_version > 0 ),',
'  constraint blog_feature_parents_ck2 check( is_active in( 0, 1 ) ),',
'  constraint blog_feature_parents_ck3 check( build_option_name != build_option_parent ),',
'  constraint blog_feature_parents_fk1 foreign key( build_option_name ) references blog_features( build_option_name ),',
'  constraint blog_feature_parents_fk2 foreign key( build_option_parent ) references blog_features( build_option_name )',
');',
'--------------------------------------------------------',
'--  Create indexes for foreign key columns',
'--------------------------------------------------------',
'create index blog_comments_ix1 on blog_comments( post_id )',
';',
'create index blog_comments_ix2 on blog_comments( parent_id )',
';',
'create index blog_posts_ix1 on blog_posts( blogger_id )',
';',
'create index blog_posts_ix2 on blog_posts( category_id )',
';',
'create index blog_feature_parents_ix1 on blog_feature_parents( build_option_parent )',
';',
'create index blog_comment_subscribers_ix1 on blog_comment_subscribers( email_id )',
';',
'create index blog_init_items_ix1 on blog_init_items( item_name )',
';',
'create index blog_post_tags_ix1 on blog_post_tags( tag_id )',
';',
'--------------------------------------------------------',
'--  Set user date format preferences',
'--------------------------------------------------------',
'begin',
'  for c1 in(',
'    select',
'      user_name',
'    , preference_name',
'    , preference_value',
'    from apex_workspace_preferences',
'    where 1 = 1',
'    and preference_name in( ''BLOG_DISPLAY_DATE_FORMAT'', ''BLOG_INPUT_DATE_FORMAT'' )',
'  ) loop',
'    apex_util.set_preference(',
'      p_preference =>',
'        case c1.preference_name',
'          when ''BLOG_DISPLAY_DATE_FORMAT''',
'            then ''PERSISTENT_ITEM_P501_DISPLAY_DATE_FORMAT''',
'          else ''PERSISTENT_ITEM_P501_INPUT_DATE_FORMAT''',
'        end',
'    , p_value      => c1.preference_value',
'    , p_user       => c1.user_name',
'    );',
'    apex_util.remove_preference(',
'      p_preference => c1.preference_name',
'    , p_user       => c1.user_name',
'    );',
'  end loop;',
'end;',
'/',
''))
);
wwv_flow_imp.component_end;
end;
/
