--------------------------------------------------------
--  DDL for Foreign Keys
--------------------------------------------------------
ALTER TABLE BLOG_COMMENTS ADD CONSTRAINT BLOG_COMMENTS_FK1 FOREIGN KEY (POST_ID)
  REFERENCES BLOG_POSTS (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE BLOG_COMMENTS ADD CONSTRAINT BLOG_COMMENTS_FK2 FOREIGN KEY (PARENT_ID)
  REFERENCES BLOG_COMMENTS (ID) ON DELETE SET NULL ENABLE;

ALTER TABLE BLOG_COMMENT_FLAGS ADD CONSTRAINT BLOG_COMMENT_FLAGS_FK1 FOREIGN KEY (COMMENT_ID)
  REFERENCES BLOG_COMMENTS (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE BLOG_COMMENT_SUBS ADD CONSTRAINT BLOG_COMMENT_SUBS_FK1 FOREIGN KEY (POST_ID)
  REFERENCES BLOG_POSTS (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE BLOG_COMMENT_SUBS ADD CONSTRAINT BLOG_COMMENT_SUBS_FK2 FOREIGN KEY (EMAIL_ID)
  REFERENCES BLOG_COMMENT_SUBS_EMAIL (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE BLOG_INIT_ITEMS ADD CONSTRAINT BLOG_INIT_ITEMS_FK1 FOREIGN KEY (ITEM_NAME)
  REFERENCES BLOG_SETTINGS (ATTRIBUTE_NAME) ENABLE;

ALTER TABLE BLOG_LINKS ADD CONSTRAINT BLOG_LINKS_FK1 FOREIGN KEY (LINK_GROUP_ID)
  REFERENCES BLOG_LINK_GROUPS (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE BLOG_POSTS ADD CONSTRAINT BLOG_POSTS_FK1 FOREIGN KEY (BLOGGER_ID)
  REFERENCES BLOG_BLOGGERS (ID) ENABLE;

ALTER TABLE BLOG_POSTS ADD CONSTRAINT BLOG_POSTS_FK2 FOREIGN KEY (CATEGORY_ID)
  REFERENCES BLOG_CATEGORIES (ID) ENABLE;

ALTER TABLE BLOG_POST_TAGS ADD CONSTRAINT BLOG_POST_TAGS_FK1 FOREIGN KEY (POST_ID)
  REFERENCES BLOG_POSTS (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE BLOG_POST_TAGS ADD CONSTRAINT BLOG_POST_TAGS_FK2 FOREIGN KEY (TAG_ID)
  REFERENCES BLOG_TAGS (ID) ENABLE;
