begin
-- Inserting into BLOG_FEATURES
blog_install.features_merge('BLOG_FEATURE_OCI_OBJECT_STORAGE',1,10,'INTERNAL',null,null,null);
blog_install.features_merge('BLOG_FEATURE_POST_SPEECH',1,20,'INTERNAL',null,null,null);
blog_install.features_merge('BLOG_FEATURE_GENERATIVE_AI',1,30,'INTERNAL',null,null,null);
blog_install.features_merge('BLOG_FEATURE_LANGUAGE_AI',1,40,'INTERNAL',null,null,null);
blog_install.features_merge('BLOG_FEATURE_LINKS',1,1110,'BLOG_FEATURE_GROUP_PAGE',null,null,null);
blog_install.features_merge('BLOG_FEATURE_FILES',1,1120,'BLOG_FEATURE_GROUP_PAGE',null,null,null);
blog_install.features_merge('BLOG_FEATURE_ABOUT',1,1130,'BLOG_FEATURE_GROUP_PAGE',null,null,null);
blog_install.features_merge('BLOG_FEATURE_SEARCH',1,1140,'BLOG_FEATURE_GROUP_PAGE',null,null,null);
blog_install.features_merge('BLOG_FEATURE_SEARCH_POSTS',1,1150,'BLOG_FEATURE_GROUP_PAGE','BLOG_FEATURE_SEARCH',null,null);
blog_install.features_merge('BLOG_FEATURE_SEARCH_COMMENTS',1,1160,'BLOG_FEATURE_GROUP_PAGE','BLOG_FEATURE_SEARCH',null,null);
blog_install.features_merge('BLOG_FEATURE_SEARCH_LINKS',1,1170,'BLOG_FEATURE_GROUP_PAGE','BLOG_FEATURE_SEARCH',null,null);
blog_install.features_merge('BLOG_FEATURE_SEARCH_FILES',1,1180,'BLOG_FEATURE_GROUP_PAGE','BLOG_FEATURE_SEARCH',null,null);
blog_install.features_merge('BLOG_FEATURE_LATEST_POSTS',1,1220,'BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,null,null);
blog_install.features_merge('BLOG_FEATURE_CATEGORY',1,1230,'BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,null,null);
blog_install.features_merge('BLOG_FEATURE_CATEGORY_POST_COUNT',1,1240,'BLOG_FEATURE_GROUP_RIGHT_COLUMN','BLOG_FEATURE_CATEGORY',null,null);
blog_install.features_merge('BLOG_FEATURE_ARCHIVE',1,1250,'BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,null,null);
blog_install.features_merge('BLOG_FEATURE_ARCHIVE_POST_COUNT',1,1260,'BLOG_FEATURE_GROUP_RIGHT_COLUMN','BLOG_FEATURE_ARCHIVE',null,null);
blog_install.features_merge('BLOG_FEATURE_TAG_CLOUD',1,1270,'BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,null,null);
blog_install.features_merge('BLOG_FEATURE_TAG_CLOUD_POST_COUNT',1,1280,'BLOG_FEATURE_GROUP_RIGHT_COLUMN','BLOG_FEATURE_TAG_CLOUD',null,null);
blog_install.features_merge('BLOG_FEATURE_RSS',1,1290,'BLOG_FEATURE_GROUP_RIGHT_COLUMN',null,null,null);
blog_install.features_merge('BLOG_FEATURE_POST_PAGINATION',1,1310,'BLOG_FEATURE_GROUP_POST',null,null,null);
blog_install.features_merge('BLOG_FEATURE_ALLOW_COMMENTS',1,1410,'BLOG_FEATURE_GROUP_COMMENTS',null,null,null);
blog_install.features_merge('BLOG_FEATURE_SUBSCRIBE_COMMENTS',1,1420,'BLOG_FEATURE_GROUP_COMMENTS','BLOG_FEATURE_ALLOW_COMMENTS',null,null);
blog_install.features_merge('BLOG_FEATURE_COMMENT_VERIFY',1,1430,'BLOG_FEATURE_GROUP_COMMENTS','BLOG_FEATURE_ALLOW_COMMENTS',null,null);
blog_install.features_merge('BLOG_FEATURE_MODERATE_COMMENTS',1,1440,'BLOG_FEATURE_GROUP_COMMENTS','BLOG_FEATURE_ALLOW_COMMENTS',null,null);
blog_install.features_merge('BLOG_FEATURE_MODERATE_COMMENTS_AI',1,1450,'BLOG_FEATURE_GROUP_COMMENTS','BLOG_FEATURE_MODERATE_COMMENTS','BLOG_FEATURE_LANGUAGE_AI','INCLUDE');
blog_install.features_merge('BLOG_FEATURE_MODAL_PAGES',1,1510,'BLOG_FEATURE_GROUP_MISC',null,null,null);
blog_install.features_merge('BLOG_FEATURE_SITEMAP',1,1520,'BLOG_FEATURE_GROUP_MISC',null,null,null);
blog_install.features_merge('BLOG_FEATURE_ATOM',1,1530,'BLOG_FEATURE_GROUP_MISC',null,null,null);
-- Inserting into BLOG_SETTINGS
blog_install.settings_merge('G_APP_VERSION',10,0,'STRING','INTERNAL',null,null,null,null,'Release 24.2.11.20260126');
blog_install.settings_merge('G_PUB_APP_ID',20,0,'STRING','INTERNAL',null,null,null,null,blog_util.int_to_vc2(apex_application_install.get_application_id));
blog_install.settings_merge('G_OCI_OS_PROXY_URL',40,1,'URL','INTERNAL',null,null,null,null,null);
blog_install.settings_merge('G_OCI_OS_NAMESPACE',50,1,'STRING','INTERNAL',null,null,null,null,null);
blog_install.settings_merge('G_OCI_OS_REGION',60,1,'STRING','INTERNAL',null,null,null,null,null);
blog_install.settings_merge('G_OCI_OS_BUCKET',70,1,'STRING','INTERNAL',null,null,null,null,null);
blog_install.settings_merge('G_OCI_OS_BUCKET_URL',80,1,'URL','INTERNAL',null,null,null,null,null);
blog_install.settings_merge('G_OCI_LANG_AI_COMPARTMENT_OCID',90,1,'STRING','INTERNAL',null,null,null,null,null);
blog_install.settings_merge('P0_BLOG_APP_NAME',1110,0,'STRING','BLOG_SETTING_GROUP_GENERAL',null,null,null,null,'My Blog');
blog_install.settings_merge('P0_BLOG_APP_DESC',1120,0,'STRING','BLOG_SETTING_GROUP_GENERAL',null,null,null,null,'About Almost Everything');
blog_install.settings_merge('G_APP_EMAIL',1130,1,'EMAIL','BLOG_SETTING_GROUP_GENERAL',null,null,null,null,null);
blog_install.settings_merge('P0_BLOG_APP_DATE_FORMAT',1210,0,'DATE_FORMAT','BLOG_SETTING_GROUP_UI',null,null,null,null,'fmDD Mon YYYY');
blog_install.settings_merge('P0_BLOG_POST_DATE_FORMAT',1220,0,'DATE_FORMAT','BLOG_SETTING_GROUP_UI',null,null,null,null,'fmDay, Month DD, YYYY');
blog_install.settings_merge('P1_BLOG_POST_ROWS',1310,0,'INTEGER','BLOG_SETTING_GROUP_REPORTS',1,50,null,null,'5');
blog_install.settings_merge('P2_BLOG_COMMENT_ROWS',1320,0,'INTEGER','BLOG_SETTING_GROUP_REPORTS',1,50,null,null,'10');
blog_install.settings_merge('G_LATEST_POST_ROWS',1330,0,'INTEGER','BLOG_SETTING_GROUP_REPORTS',1,20,null,null,'5');
blog_install.settings_merge('P0_BLOG_SEARCH_ROWS',1340,0,'INTEGER','BLOG_SETTING_GROUP_REPORTS',1,50,null,null,'10');
blog_install.settings_merge('G_COMMENT_WATCH_MONTHS',1410,0,'INTEGER','BLOG_SETTING_GROUP_COMMENTS',1,6,null,null,'1');
blog_install.settings_merge('G_MAX_AGE_DOWNLOAD',1510,0,'INTEGER','BLOG_SETTING_GROUP_FILE_REPO',0,31536000,'BLOG_FEATURE_OCI_OBJECT_STORAGE','EXCLUDE','14400');
blog_install.settings_merge('G_MAX_AGE_FILE',1520,0,'INTEGER','BLOG_SETTING_GROUP_FILE_REPO',0,31536000,'BLOG_FEATURE_OCI_OBJECT_STORAGE','EXCLUDE','604800');
blog_install.settings_merge('G_MAX_AGE_SITEMAP',1610,0,'INTEGER','BLOG_SETTING_GROUP_SITEMAP',0,31536000,null,null,'3600');
blog_install.settings_merge('G_MAX_AGE_RSS',1710,0,'INTEGER','BLOG_SETTING_GROUP_RSS',0,31536000,null,null,'3600');
blog_install.settings_merge('G_MAX_AGE_RSS_XSL',1720,0,'INTEGER','BLOG_SETTING_GROUP_RSS',0,31536000,null,null,'604800');
blog_install.settings_merge('G_RSS_URL',1730,1,'URL','BLOG_SETTING_GROUP_RSS',null,null,null,null,null);
blog_install.settings_merge('G_RSS_XSL_URL',1740,1,'URL','BLOG_SETTING_GROUP_RSS',null,null,null,null,null);
blog_install.settings_merge('G_CANONICAL_HOST',1810,1,'URL','BLOG_SETTING_GROUP_SEO',null,null,null,null,null);
-- Inserting into BLOG_LIST_OF_VALUES
blog_install.list_of_values_ins(1,10,'COMMENT_FLAG','NEW','BLOG_LOV_COMMENT_FLAG_NEW');
blog_install.list_of_values_ins(1,20,'COMMENT_FLAG','UNREAD','BLOG_LOV_COMMENT_FLAG_UNREAD');
blog_install.list_of_values_ins(1,30,'COMMENT_FLAG','REPLY','BLOG_LOV_COMMENT_FLAG_REPLY');
blog_install.list_of_values_ins(1,40,'COMMENT_FLAG','READ','BLOG_LOV_COMMENT_FLAG_READ');
blog_install.list_of_values_ins(1,10,'COMMENT_STATUS','ENABLED','BLOG_TXT_ENABLED');
blog_install.list_of_values_ins(1,20,'COMMENT_STATUS','DISABLED','BLOG_TXT_DISABLED');
blog_install.list_of_values_ins(1,30,'COMMENT_STATUS','MODERATE','BLOG_LOV_COMMENT_STATUS_MODERATE');
blog_install.list_of_values_ins(1,10,'IS_ACTIVE','1','BLOG_TXT_ENABLED');
blog_install.list_of_values_ins(1,20,'IS_ACTIVE','0','BLOG_TXT_DISABLED');
blog_install.list_of_values_ins(1,10,'LINK_STATUS','ENABLED','BLOG_TXT_ENABLED');
blog_install.list_of_values_ins(1,20,'LINK_STATUS','DISABLED','BLOG_TXT_DISABLED');
blog_install.list_of_values_ins(1,30,'LINK_STATUS','GROUP_DISABLED','BLOG_LOV_LINK_STATUS_GROUP_DISABLED');
blog_install.list_of_values_ins(1,10,'POST_STATUS','PUBLISHED','BLOG_LOV_POST_STATUS_PUBLISHED');
blog_install.list_of_values_ins(1,20,'POST_STATUS','SCHEDULED','BLOG_LOV_POST_STATUS_SCHEDULED');
blog_install.list_of_values_ins(1,30,'POST_STATUS','DRAFT','BLOG_LOV_POST_STATUS_DRAFT');
blog_install.list_of_values_ins(1,40,'POST_STATUS','CATEGORY_DISABLED','BLOG_LOV_POST_STATUS_CATEGORY_DISABLED');
blog_install.list_of_values_ins(1,50,'POST_STATUS','BLOGGER_DISABLED','BLOG_LOV_POST_STATUS_BLOGGER_DISABLED');
blog_install.list_of_values_ins(1,10,'YES_NO','0','BLOG_LOV_YES_NO_NO');
blog_install.list_of_values_ins(1,20,'YES_NO','1','BLOG_LOV_YES_NO_YES');
-- Inserting into BLOG_INIT_ITEMS
blog_install.init_items_ins;
end;
/
