--REM INSERTING into BLOG_PARAM
--SET DEFINE OFF;
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('ALLOW_COMMENT','Y','Allow comments','Y','If set to "<b>Yes</b>", readers can post comments to any article.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('BLOG_EMAIL','Y','Blog email','blog@blogexample.org','Email address witch is used notification emails from field.','TEXT','Y','EMAIL',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('COMMENT_VERIFY_QUESTION','Y','Show math question','Y','If set to "<b>Yes</b>", small math question is displayed in comment and contact page. This <b>might</b> prevent bots posting comments to articles.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('FILE_DOWNLOAD_ENABLED','Y','Allow file download','Y','If set to "<b>Yes</b>", access to file repository URL for downloads is allowed.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('FOLLOWUP_EMAIL_BODY','Y','Followup email body','Hi #NICK_NAME#,

You have chosen to receive follow up notification if new comment is posted to article "#ARTICLE_TITLE#".
To follow up the article new comment(s), please go to:
#ARTICLE_URL#

If you wish not get notification email in future please go to:
#UNSUBSCRIBE_URL#

Best regards,
#BLOG_NAME#','Email message body for readers who have post comment about new comment/author reply on article.','TEXTAREA','Y','EMAIL',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('FOLLOWUP_EMAIL_SUBJ','Y','Followup email subject','New comment on #BLOG_NAME# article: #ARTICLE_TITLE#.','Email subject for readers who have post comment about new comment/author reply on article.','TEXT','Y','EMAIL',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_ARTICLE_ROWS','Y','Article per pagination','3','How many articles is shown per pagination e.g. in blog home page.','NUMBER','N','UI',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_BASE_URL','Y','Canonical URL','http://vbox-apex/apex/','Canonical URL is useful to solve www and non-www duplicate content—where two URLs, identical except that one begins with "www" and other does not, point to the same page.','TEXT','N','SEO',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_BING_WEBMASTER_META','Y','Bing webmaster tools verification meta tag',null,null,'TEXT','Y','SEO',null,'A');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_BLOG_DESCRIPTION','Y','Blog description','Blogging about all stuff','Description of blog. Optionally, controlled by preference "<b>Show blog description</b>", this is shown in blog reader.','TEXT','N','UI',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_BLOG_NAME','Y','Blog name','My Blog','Blog name displayed in blog reader.','TEXT','N','UI',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_BLOG_READER_APP_ID','N','Blog reader application id','290','Used for query blog reader application alias. Only for developers.','NUMBER','N','INTERNAL',null,'A');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_COMMENT_ROWS','Y','Comments per pagination','10','How many comments is shown per pagination e.g. in blog article page.','NUMBER','N','UI',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_DATE_FORMAT','Y','Date format','fmDD Mon YYYY','Blog reader date format used e.g. when article is posted.','TEXT','N','UI',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_GOOGLE_ANALYTICS_JS_CODE','Y','Google Analytics tracking ID',null,null,'TEXTAREA','Y','SEO',null,'A');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_GOOGLE_WEBMASTER_META','Y','Google webmaster tools verification meta tag',null,null,'TEXT','Y','SEO',null,'A');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_RSS_FEED_URL','Y','RSS feed URL','f?p=BLOG:RSS:0','Blog RSS feed URL. Default is f?p=&lt;blog application alias&gt;:RSS:0. Tip: You can "burn" blog feed in <a target="balnk" href="http://feedburner.google.com">Feedburner</a> and use burned feed full URL here.','TEXT','Y','RSS','SHOW_RSS_FEED','B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('G_THEME_PATH','Y','Theme location','f?p=290:FILES:0:APPLICATION_PROCESS=DOWNLOAD:::P11_FILE_NAME:','HTTP server folder where theme is located.','TEXT','N','UI',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('LOGGING_ENABLED','Y','Log activity','Y','If set to "<b>Yes</b>", new sessions, article access, category access and users search are logged. Setting this to "<b>No</b>" <u>may</u> increase performance.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('LOG_ROTATE_DAY','N','Rotate log after days','14','Logs rotate interval for application logs. Nothing to do with APEX engine logs. In future release this might be controlled by author. Currently only developer can change this attribute and it do affect only when blog is installed. Changing this already installed blog don''t have any affects.','NUMBER','N','INTERNAL',null,'A');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('MODERATION_ENABLED','Y','Comments moderate','N','If set to "<b>Yes</b>", all comments must be moderated and approved by blog author(s).','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('NEW_COMMENT_EMAIL_BODY','Y','Author notify email body','Hi #AUTHOR_NAME#,

New comment is posted to article "#ARTICLE_TITLE#".
#ARTICLE_URL#

Best regards,
#BLOG_NAME#','Email message body for author about new comment on article.','TEXTAREA','Y','EMAIL',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('NEW_COMMENT_EMAIL_SUBJ','Y','Author notify email subject','New comment on #BLOG_NAME# article: #ARTICLE_TITLE#.','Email subject for author about new comment on article.','TEXT','Y','EMAIL',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('RSS_DESCRIPTION','Y','RSS feed description','My Blog most recent articles','Description for blog RSS feed.','TEXT','Y','RSS','SHOW_RSS_FEED','B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SCHEMA_VERSION','N','Blog engine version id','2.9.0.1','Used on future releases for upgrade. Only for developers.','TEXT','N','INTERNAL',null,'A');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_ABOUT_PAGE','Y','Show about page/tab','Y','If set to "<b>Yes</b>", about page can be accessed from blog reader.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_AUTHOR_PAGE','Y','Show authors tab/page','Y','If set to "<b>Yes</b>", authors page can be accessed from blog reader.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_BLOG_DESCRIPTION','Y','Show blog description','Y','If set to "<b>Yes</b>", blog description is visible in blog reader pages under blog name.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_BLOG_REPORT','Y','Show blogroll','Y','If set "<b>Yes</b>", blogroll list is shown on blog reader resource page.','YESNO','N','AUTH','SHOW_RESOURCE_PAGE','B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_CONTACT_PAGE','N','Show contact form tab/page','N','If set to "<b>Yes</b>", contact form page can be accessed from blog reader.

!!! DO NOT USE. FEATURE NOT IMPLEMENTED !!! ','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_DISCLAIMER_PAGE','Y','Show disclaimer page/tab','Y','If set to "<b>Yes</b>", disclaimer page can be accessed from blog reader.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_FAQ_PAGE','Y','Show FAQ tab/page','Y','If set to "<b>Yes</b>", frequently asked questions (FAQ) page can be accessed from blog reader.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_FILE_PAGE','Y','Show files tab/page','Y','If set to "<b>Yes</b>", files page can be accessed from blog reader.','YESNO','N','AUTH','FILE_DOWNLOAD_ENABLED','B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_FOOTER','Y','Show footer text','Y','If set to "<b>Yes</b>", footer text is shown in every blog reader page. Foter text is maintained from settings -> messages (BLOG_READER_FOOTER).','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_PHOTOS_PAGE','Y','Show photos tab/page','Y','If set to "<b>Yes</b>", files page can be accessed from blog reader.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_RESOURCE_PAGE','Y','Show resources page/tab','Y','If set to "<b>Yes</b>", resources page can be accessed from blog reader.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_RESOURCE_REPORT','Y','Show useful links','Y','If set to "<b>Yes</b>", useful links list is shown on blog reader resource page.','YESNO','N','AUTH','SHOW_RESOURCE_PAGE','B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_RSS_FEED','Y','Publish RSS feed','Y','If set to "<b>Yes</b>", RSS fead is published on URL &G_BASE_URL.f?p=&G_BLOG_READER_APP_ALIAS.:RSS. Also RSS feed logo is shown in blog reader global page.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SHOW_VISITOR_PAGE','Y','Show visitor page/tab','Y','If set to "<b>Yes</b>", visitors map page can be accessed from blog reader.','YESNO','N','AUTH',null,'B');
Insert into BLOG_PARAM (PARAM_ID,EDITABLE,PARAM_NAME,PARAM_VALUE,PARAM_HELP,PARAM_TYPE,PARAM_NULLABLE,PARAM_GROUP,PARAM_PARENT,PARAM_USE_SKILL) values ('SITEMAP_ENABLED','Y','Publish sitemap','Y','If set to "<b>Yes</b>", sitemap is published on URL &G_BASE_URL.f?p=&G_BLOG_READER_APP_ALIAS.:SITEMAP.','YESNO','N','AUTH',null,'B');
