BEGIN
    blog_install.blog_install.set_jobs(true);
END;
/
ALTER TABLE "BLOG_COMMENT" DROP CONSTRAINT "BLOG_COMMENT_FK3"
/
ALTER TABLE "BLOG_ARTICLE_LOG" DROP CONSTRAINT "BLOG_ARTICLE_LOG_FK1"
/
ALTER TABLE "BLOG_COMMENT" DROP CONSTRAINT "BLOG_COMMENT_FK2"
/
ALTER TABLE "BLOG_COMMENT_NOTIFY" DROP CONSTRAINT "BLOG_COMMENT_NOTIFY_FK1"
/
ALTER TABLE "BLOG_FILE_LOG" DROP CONSTRAINT "BLOG_FILES_LOG_FK1"
/
ALTER TABLE "BLOG_ARTICLE" DROP CONSTRAINT "BLOG_ARTICLE_FK1"
/
ALTER TABLE "BLOG_CONTACT_MESSAGE" DROP CONSTRAINT "BLOG_CONTACT_MESSAGE_FK1";
/
ALTER TABLE "BLOG_AUTHOR" DROP CONSTRAINT "BLOG_AUTHOR_FK1"
/
ALTER TABLE "BLOG_COMMENT" DROP CONSTRAINT "BLOG_COMMENT_FK1"
/
ALTER TABLE "BLOG_COMMENT_NOTIFY" DROP CONSTRAINT "BLOG_COMMENT_NOTIFY_FK2"
/
ALTER TABLE "BLOG_CATEGORY_LOG" DROP CONSTRAINT "BLOG_CATEGORY_LOG_FK1"
/
ALTER TABLE "BLOG_ARTICLE" DROP CONSTRAINT "BLOG_ARTICLE_FK2"
/
ALTER TABLE  BLOG_ARTICLE_HIT20 DROP CONSTRAINT BLOG_ARTICLE_HIT20_FK1
/
ALTER TABLE  BLOG_ARTICLE_LAST20 DROP CONSTRAINT BLOG_ARTICLE_LAST20_FK1
/
ALTER TABLE  BLOG_ARTICLE_TOP20 DROP CONSTRAINT BLOG_ARTICLE_TOP20_FK1
/
ALTER TABLE  BLOG_COMMENT_LOG DROP CONSTRAINT BLOG_COMMENT_LOG_FK1
/
ALTER TABLE  BLOG_PARAM_APP DROP CONSTRAINT BLOG_PARAM_APP_FK1
/
DROP TABLE "BLOG_COMMENT"
/    
DROP TABLE "BLOG_FAQ"
/    
DROP TABLE "BLOG_FILE_LOG"
/    
DROP TABLE "BLOG_COMMENT_BLOCK"
/    
DROP TABLE "BLOG_CONTACT_MESSAGE"
/
DROP TABLE "BLOG_ACTIVITY_LOG2"
/
DROP TABLE "BLOG_PARAM"
/    
DROP TABLE "BLOG_COUNTRY"
/
DROP TABLE "BLOG_ARTICLE"
/
DROP TABLE "BLOG_FILE"
/
DROP TABLE "BLOG_ARTICLE_PREVIEW"
/
DROP TABLE "BLOG_AUTHOR"
/
DROP TABLE "BLOG_COMMENT_USER"
/
DROP TABLE "BLOG_CATEGORY"
/
DROP TABLE "BLOG_ARTICLE_LOG"
/
DROP TABLE "BLOG_CATEGORY_LOG"
/
DROP TABLE "BLOG_RESOURCE"
/
DROP TABLE "BLOG_ACTIVITY_LOG1"
/
DROP TABLE "BLOG_COMMENT_NOTIFY"
/
DROP TABLE "BLOG_LONG_TEXT";
/
DROP TABLE "BLOG_HTTP410"
/
DROP VIEW "BLOG_V$ACTIVITY"
/    
DROP VIEW "BLOG_V$ACTIVITY_LOG"
/    
DROP VIEW "BLOG_V$ARTICLE"
/    
DROP SYNONYM "BLOG_ACTIVITY_LOG"
/
DROP SEQUENCE "BLOG_SEQ"
/    
DROP MATERIALIZED VIEW "BLOG_ARTICLE_TOP20"
/
DROP MATERIALIZED VIEW "BLOG_ARTICLE_LAST20"
/    
DROP MATERIALIZED VIEW "BLOG_ARTICLE_HIT20"
/    
DROP MATERIALIZED VIEW "BLOG_ARCHIVE_LOV"
/
DROP MATERIALIZED VIEW "BLOG_COMMENT_LOG"
/
DROP MATERIALIZED VIEW BLOG_PARAM_APP
/
DROP PACKAGE BLOG_ADMIN_APP
/    
DROP PACKAGE BLOG_JOB
/
DROP PACKAGE BLOG_PLUGIN
/
DROP PACKAGE BLOG_LOG
/    
DROP PACKAGE BLOG_UTIL
/    
DROP PACKAGE BLOG_XML
/
DROP PACKAGE BLOG_INSTALL
/    
DROP FUNCTION BLOG_SGID
/
DROP FUNCTION BLOG_PW_HASH
/